### ISSUE TITLE
When badging in, indicate which team you are joining

### ISSUE THREAD

**Issue by ovidio-peduri** [jusroberts/pingpong-web-server#20]
Right now, there's no indication of which team you are about to join. We should indicate that. Perhaps something like "Team A badge in!" and then "Team B badge in!"

**Comment by dvankley** [comment]
That's what the "player x scan" button is intended for. We can just change that to team names if you think that makes more sense.

**Comment by ovidio-peduri** [comment]
I think that makes enough sense. This may be unnecessary in that case
